[package]
name = "transcribed-sanity-valve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
pulldown-cmark = "0.9.2"
lazy_static = "1.4.0"
maud = "*"
chrono = "0.4.22"
