on:
  push:
    branches: [ "site", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo run
      - run: mkdir _html
      - run: echo 'hello' > _html/index.html
      - uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: _html
      - uses: actions/deploy-pages@v1.0.10
